import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  const color = 'yellow';
  return (
    <html lang="en">
      <body  className="h-screen w-screen flex flex-col ">
        <div className='w-screen h-20 bg-yellow-300'></div>
        {children}
        </body>
    </html>
  )
}
