

export enum Action {
    CREATE = "CREATE",
    UPDATE = "UPDATE",
    UPDATEOWNER = "UPDATEOWNER",
    UPDATEPICTURE = "UPDATEPICTURE",
    UPDATENAME = "UPDATENAME",
    UPDATEDESCRIPTION = "UPDATEDESCRIPTION",
    DELETE = "DELETE",
    REDO = "REDO",
    COMPLETE = "COMPLETE"
}
