
export enum TypeOfNotification {

    CHANGETASK = "CHANGETASK" ,
    ADDORREMOVEINGROUP = "ADDORREMOVEINGROUP" ,
    CHANGEPERMISSION = "CHANGEPERMISSION" ,
    POINTS = "POINTS" ,
    SCHEDULE = "SCHEDULE" ,
    DEADLINE = "DEADLINE" ,
    CHAT = "CHAT" ,
    COMMENT = "COMMENT"
}
