export  enum TypePermission {
    UPDATE = "UPDATE",
    DELETE = "DELETE",
    CREATE = "CREATE",
    UPDATE_DELETE = "UPDATE_DELETE",
    UPDATE_CREATE = "UPDATE_CREATE",
    DELETE_CREATE = "DELETE_CREATE",
    UPDATE_DELETE_CREATE = "UPDATE_DELETE_CREATE",
    READ = "READ"
}
