
export enum TypeOfNotification {

    CHANGETASK = "CHANGETASK" ,
    ADDINGROUP = "ADDINGROUP" ,
    REMOVEINGROUP = "REMOVEINGROUP" ,
    CHANGEPERMISSION = "CHANGEPERMISSION" ,
    POINTS = "POINTS" ,
    SCHEDULE = "SCHEDULE" ,
    DEADLINE = "DEADLINE" ,
    CHAT = "CHAT" ,
    COMMENTS = "COMMENTS",
    INVITETOPROJECT = "INVITETOPROJECT"
}
